lab: datascience
source_docx: "https://microsoft.sharepoint.com/teams/ASDIPRelease/_layouts/15/Doc.aspx?sourcedoc=%7B3075C8FF-C5FF-4C56-9680-78337F468304%7D&file=Data%20Science%20Tutorial.docx&action=default&mobileredirect=true"
converted_at: "2026-09-15T13:59:13.187+01:00"
urls:
  - url: https://learn.microsoft.com/en-us/fabric/get-started/microsoft-fabric-overview
    context: "referenced under \"<a id=\"_Toc201305746\"></a>Introduction\""
  - url: https://learn.microsoft.com/en-us/power-bi/enterprise/service-admin-premium-purchase
    context: "referenced under \"<a id=\"_Toc201305747\"></a>Prerequisites\""
  - url: https://learn.microsoft.com/en-us/fabric/enterprise/buy-subscription
    context: "referenced under \"<a id=\"_Toc201305747\"></a>Prerequisites\""
  - url: https://learn.microsoft.com/en-us/fabric/get-started/fabric-trial
    context: "referenced under \"<a id=\"_Toc201305747\"></a>Prerequisites\""
  - url: https://mlflow.org/docs/latest/index.html
    context: "referenced under \"<a id=\"_Toc201305749\"></a>Different components of Data science scenario\""
  - url: https://docs.delta.io/latest/index.html
    context: "referenced under \"<a id=\"_Toc201305749\"></a>Different components of Data science scenario\""
  - url: https://seaborn.pydata.org/
    context: "referenced under \"<a id=\"_Toc201305755\"></a>Module 2: Explore data\""
  - url: https://learn.microsoft.com/en-us/fabric/data-science/data-wrangler
    context: "referenced under \"<a id=\"_Toc201305755\"></a>Module 2: Explore data\""
  - url: https://learn.microsoft.com/en-us/fabric/data-science/media/tutorial-data-science-explore-notebook/preview.png#lightbox
    context: "referenced under \"<a id=\"_Toc201305758\"></a>__Use Data Wrangler to perform initial data cleaning__\""
  - url: https://learn.microsoft.com/en-us/fabric/data-science/media/tutorial-data-science-explore-notebook/drop-duplicate.png#lightbox
    context: "referenced under \"<a id=\"_Toc201305759\"></a>__Drop duplicate rows__\""
  - url: https://learn.microsoft.com/en-us/fabric/data-science/media/tutorial-data-science-explore-notebook/drop-missing.png#lightbox
    context: "referenced under \"<a id=\"_Toc201305760\"></a>__Drop rows with missing data__\""
  - url: https://learn.microsoft.com/en-us/fabric/data-science/media/tutorial-data-science-explore-notebook/drop-columns.png#lightbox
    context: "referenced under \"<a id=\"_Toc201305761\"></a>__Drop Columns__\""
  - url: https://aka.ms/fabric/create-environment
    context: "referenced under \"<a id=\"_Toc201305772\"></a>Module 3: Train and register machine learning models\""
  - url: https://learn.microsoft.com/en-us/fabric/data-engineering/library-management#scenario-1-admin-sets-default-libraries-for-the-workspace
    context: "referenced under \"<a id=\"_Toc201305772\"></a>Module 3: Train and register machine learning models\""
  - url: https://learn.microsoft.com/en-us/fabric/data-engineering/environment-workspace-migration
    context: "referenced under \"<a id=\"_Toc201305772\"></a>Module 3: Train and register machine learning models\""
  - url: https://aka.ms/fabric-autologging
    context: "referenced under \"<a id=\"_Toc201305774\"></a>__Generate experiment for tracking and logging the model using MLflow__\""
  - url: https://imbalanced-learn.org/stable/references/generated/imblearn.over_sampling.SMOTE.html
    context: "referenced under \"<a id=\"_Toc201305779\"></a>__Apply SMOTE to the training data to synthesize new samples for the minority class__\""
  - url: https://imbalanced-learn.org/stable/over_sampling.html#smote-adasyn
    context: "referenced under \"<a id=\"_Toc201305779\"></a>__Apply SMOTE to the training data to synthesize new samples for the minority class__\""
  - url: https://learn.microsoft.com/en-us/fabric/data-science/media/tutorial-data-science-train-models/filter-workspace.png#lightbox
    context: "referenced under \"<a id=\"_Toc201305781\"></a>__Experiments artifact for tracking model performance__\""
  - url: https://learn.microsoft.com/en-us/fabric/data-science/media/tutorial-data-science-train-models/experiment-runs.png#lightbox
    context: "referenced under \"<a id=\"_Toc201305781\"></a>__Experiments artifact for tracking model performance__\""
  - url: https://aka.ms/samples/frauddectection
    context: "referenced under \"<a id=\"_Toc201305783\"></a>__Show True/False Positives/Negatives using the Confusion Matrix__\""
  - url: https://learn.microsoft.com/en-us/fabric/data-science/model-scoring-predict
    context: "referenced under \"<a id=\"_Toc201305784\"></a>Module 4: Perform batch scoring and save predictions to a Lakehouse\""
  - url: https://learn.microsoft.com/fabric/data-science/tutorial-data-science-train-models
    context: "referenced under \"<a id=\"_Toc201305784\"></a>Module 4: Perform batch scoring and save predictions to a Lakehouse\""
  - url: https://aka.ms/fabric/predict-from-model-item
    context: "referenced under \"<a id=\"_Toc201305789\"></a>__PREDICT with a user\\-defined function \\(UDF\\)__\""
  - url: https://learn.microsoft.com/en-us/fabric/data-science/tutorial-data-science-batch-scoring
    context: "referenced under \"<a id=\"_Toc201305791\"></a>Module 5: Visualize predictions with a Power BI report\""
  - url: https://learn.microsoft.com/en-us/fabric/data-science/media/tutorial-data-science-create-report/churn-rate.png#lightbox
    context: "referenced under \"<a id=\"_Toc201305793\"></a>__Add new measures__\""
  - url: https://learn.microsoft.com/en-us/fabric/data-science/media/tutorial-data-science-create-report/card-churn.png#lightbox
    context: "referenced under \"<a id=\"_Toc201305794\"></a>__Create new report__\""
  - url: https://learn.microsoft.com/en-us/fabric/data-science/media/tutorial-data-science-create-report/age.png#lightbox
    context: "referenced under \"<a id=\"_Toc201305794\"></a>__Create new report__\""
  - url: https://learn.microsoft.com/en-us/fabric/data-science/media/tutorial-data-science-create-report/number-of-products.png#lightbox
    context: "referenced under \"<a id=\"_Toc201305794\"></a>__Create new report__\""
  - url: https://learn.microsoft.com/en-us/fabric/data-science/media/tutorial-data-science-create-report/new-credit-score.png#lightbox
    context: "referenced under \"<a id=\"_Toc201305794\"></a>__Create new report__\""
  - url: https://learn.microsoft.com/en-us/fabric/data-science/media/tutorial-data-science-create-report/change-title.png#lightbox
    context: "referenced under \"<a id=\"_Toc201305794\"></a>__Create new report__\""
  - url: https://learn.microsoft.com/en-us/fabric/data-science/media/tutorial-data-science-create-report/germany-spain-france.png#lightbox
    context: "referenced under \"<a id=\"_Toc201305794\"></a>__Create new report__\""
