-- 01-create-tables.sql
-- Generated by /vbd-lab-foundation for Contoso Health. Verified 2026-09-15.

CREATE SCHEMA analytics;
GO

CREATE TABLE analytics.dim_provider (
    provider_id      INT           NOT NULL,
    provider_name    VARCHAR(200)  NOT NULL,
    speciality       VARCHAR(80)   NULL,
    state            CHAR(2)       NULL
);

CREATE TABLE analytics.fact_provider_month_summary (
    provider_id      INT           NOT NULL,
    month            DATE          NOT NULL,
    total_paid       DECIMAL(18,2) NOT NULL,
    claim_count      INT           NOT NULL,
    avg_claim        DECIMAL(18,2) NOT NULL
);
