lab: rti
source_docx: "https://microsoft.sharepoint.com/teams/ASDIPRelease/_layouts/15/Doc.aspx?sourcedoc=%7B41DF8990-E54D-48EC-94CC-08080F5AAEEF%7D&file=Real-time%20Intelligence%20Tutorial.docx&action=default&mobileredirect=true"
converted_at: "2026-09-15T13:59:13.187+01:00"
urls:
  - url: https://learn.microsoft.com/en-us/fabric/real-time-intelligence/event-streams/overview
    context: "referenced under \"<a id=\"_Toc192599817\"></a>Scenario\""
  - url: https://learn.microsoft.com/en-us/fabric/real-time-intelligence/eventhouse
    context: "referenced under \"<a id=\"_Toc192599817\"></a>Scenario\""
  - url: https://learn.microsoft.com/en-us/fabric/real-time-intelligence/create-database
    context: "referenced under \"<a id=\"_Toc192599817\"></a>Scenario\""
  - url: https://learn.microsoft.com/en-us/fabric/real-time-intelligence/create-query-set
    context: "referenced under \"<a id=\"_Toc192599817\"></a>Scenario\""
  - url: https://learn.microsoft.com/en-us/fabric/real-time-intelligence/dashboard-real-time-create
    context: "referenced under \"<a id=\"_Toc192599817\"></a>Scenario\""
  - url: https://learn.microsoft.com/en-us/power-bi/enterprise/service-admin-premium-purchase
    context: "referenced under \"<a id=\"_Toc192599818\"></a>Prerequisites\""
  - url: https://app.fabric.microsoft.com/
    context: "referenced under \"<a id=\"_Toc192599819\"></a>Module 1: Create a Fabric workspace\""
  - url: https://learn.microsoft.com/en-us/fabric/real-time-intelligence/media/tutorial/event-stream-edit-button.png#lightbox
    context: "referenced under \"<a id=\"_Toc192599822\"></a>Create an Eventstream\""
  - url: https://learn.microsoft.com/en-us/fabric/real-time-intelligence/media/tutorial/add-all-fields.png#lightbox
    context: "referenced under \"<a id=\"_Toc192599822\"></a>Create an Eventstream\""
  - url: https://learn.microsoft.com/en-us/fabric/real-time-intelligence/media/tutorial/select-built-in-function.png#lightbox
    context: "referenced under \"<a id=\"_Toc192599822\"></a>Create an Eventstream\""
  - url: https://learn.microsoft.com/en-us/fabric/real-time-intelligence/media/tutorial/pencil-on-event-house.png#lightbox
    context: "referenced under \"<a id=\"_Toc192599823\"></a>__Create a destination for the timestamp transformation__\""
  - url: https://learn.microsoft.com/en-us/fabric/fundamentals/copilot-real-time-intelligence
    context: "referenced under \"<a id=\"_Toc192599831\"></a>__Write a KQL query__\""
  - url: https://learn.microsoft.com/en-us/fabric/real-time-intelligence/media/tutorial/bikes-timechart.png#lightbox
    context: "referenced under \"<a id=\"_Toc192599831\"></a>__Write a KQL query__\""
  - url: https://github.com/microsoft/fabric-samples/blob/main/docs-samples/real-time-intelligence/tutorial-commands-script.kql
    context: "referenced under \"<a id=\"_Toc192599832\"></a>__Create a materialized view__\""
  - url: https://learn.microsoft.com/en-us/fabric/real-time-intelligence/media/tutorial/second-visual-report.png#lightbox
    context: "referenced under \"<a id=\"_Toc192599840\"></a>__Add visualizations to the report__\""
